export default {
  icHome: require("../../assets/icons/house.png"),
  icUser: require("../../assets/icons/account.png"),
  icInfo: require("../../assets/icons/info.png"),
  icEye: require("../../assets/icons/eye.png"),
  icEyeOff: require("../../assets/icons/eyeoff.png"),
  iconicap: require("../../assets/icons/icapicon.png"),
  fondob: require("../../assets/icons/INMOBICAPITALsBLANCO.png"),
  icMoney: require("../../assets/icons/monei.png"),
  icMoneyinv: require("../../assets/icons/moneyinv.png"),
  iconlogo: require("../../assets/icons/INMOBICAPITALELEMENTOVISUAL1.png"),
  homeimg: require("../../assets/icons/LOGOBLANCO.png"),
  icperfil: require("../../assets/icons/myperfil.png"),
  icregistro: require("../../assets/icons/verify.png"),
  camara: require("../../assets/icons/addcamara.png"),
  addcamara: require("../../assets/icons/addphoto.png"),
  misdatos: require("../../assets/icons/misdatos.png"),
  inversion: require("../../assets/icons/inversion.png"),
  phone:require("../../assets/icons/phonec.png"),
  mail:require("../../assets/icons/mail.png")
};
